#!/system/bin/sh

# shellcheck shell=ksh
# shellcheck disable=SC2059

if [ "$(id -u)" -ne 0 ]; then
    current_script="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
    quoted_args=$(printf " %q" "$@")
    exec su -M -c "exec '$current_script'$quoted_args"
fi
ScriptDir="$(cd "$(dirname "$0")" && pwd)"
PATH="$ScriptDir:$PATH"
BasePath="/data/local/chroot"

if [ ! -d "$BasePath" ]; then
    echo "错误: 目录 '$BasePath' 不存在。" >&2
    exit 1
fi

FMT="%-16s %-12s %-10s\n"

printf "$FMT" "name" "process" "ismounted"
printf "$FMT" "----" "-------" "---------"

for dir in "$BasePath"/*; do
    if [ -d "$dir" ]; then
        name="${dir##*/}"

        pid_count=$(chroot-proc "$name" pids 2> /dev/null | wc -l)
        pid_count=$((pid_count + 0))

        if chroot-checkmount "$name" > /dev/null 2>&1; then
            mnt_status="Yes"
        else
            mnt_status="No"
        fi

        printf "$FMT" "$name" "$pid_count" "$mnt_status"
    fi
done
