#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

if [ "$(id -u)" -ne 0 ]; then
    current_script="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
    quoted_args=$(printf " %q" "$@")
    exec su -M -c "exec '$current_script'$quoted_args"
fi
ScriptDir="$(cd "$(dirname "$0")" && pwd)"

# 启用此段以使用 makepkg 风格输出
if [[ ! -f "$ScriptDir/lib/message.sh" ]]; then
    echo "错误: 未找到 $ScriptDir/lib/message.sh" >&2
    exit 1
fi
source "$ScriptDir/lib/message.sh"
QUIET=0
colorize

# 启用此行以使用其它自定义脚本
PATH="$ScriptDir:$PATH"
# 启用以下两行以使用 Termux 中的二进制程序和库
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
PATH="/data/data/com.termux/files/usr/bin:$PATH"

BasePath="/data/local/chroot"

usage() {
    cat << EOF
归档 chroot 根文件系统。

用法: ${0##*/} <Name> <BackupDir>

参数:
  Name         chroot 环境的名称
  BackupDir    归档文件存放的目标目录
EOF
    exit 1
}

Name="$1"
BackupDir="$2"
[[ -z "$Name" ]] && {
    error "未提供名称。"
    usage
}
[[ -z "$BackupDir" ]] && {
    error "未提供备份目录。"
    usage
}

mkdir -p "$BackupDir"
RootFs="$BasePath/$Name"
[[ -d "$RootFs" ]] || {
    error "目录 '$RootFs' 不存在。"
    exit 1
}

TermuxTmp="/data/data/com.termux/files/usr/tmp"
TarExcludeOpts=()
DuExcludeOpts=()

if is-mounted "$TermuxTmp" "$RootFs/tmp"; then
    TarExcludeOpts+=(--exclude="$(basename "$RootFs")/tmp")
    DuExcludeOpts+=(--exclude="$RootFs/tmp")
fi

msg "统计存储占用..."
RawSize=$(du -sbx "${DuExcludeOpts[@]}" "$RootFs" 2> /dev/null | awk "{print \$1}")
HumanSize=$(du -shx "${DuExcludeOpts[@]}" "$RootFs" 2> /dev/null | awk "{print \$1}")

msg "开始归档..."
BackupFile="$BackupDir/$Name-$(date +'[%y]%m.%d-%H:%M:%S').tar.zst"
msg2 "%s %s -> %s" "$HumanSize" "$Name" "$BackupFile"

tar -cpf - \
    --one-file-system --warning=no-file-ignored \
    "${TarExcludeOpts[@]}" \
    -C "$(dirname "$RootFs")" \
    "$(basename "$RootFs")" 2> /dev/null \
    | pv -s "$RawSize" \
    | zstd -T0 > "$BackupFile"

if [ -f "$BackupFile" ]; then
    msg "归档完成。"
else
    warning "归档文件未生成。"
    exit 1
fi
