#!/system/bin/sh

# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

LinaRoot="$(dirname "$(readlink -f "$0")")"
GitBranch="$(git -C "$LinaRoot" rev-parse --abbrev-ref HEAD)"
LINA_VERSION="r$(git -C "$LinaRoot" rev-list --count HEAD)-$(git -C "$LinaRoot" rev-parse --short HEAD)"
Modules="$LinaRoot/cells"
Self="${0##*/}"

[[ -f "$LinaRoot/lib/ui.sh" ]] || {
    echo "错误: 未找到 $LinaRoot/lib/ui.sh" >&2
    exit 1
}
source "$LinaRoot/lib/ui.sh"

[[ -f "$LinaRoot/.lina-dev" ]] || {
    [[ -f "$LinaRoot/update.lock" ]] && {
        echo "$Self 上次启动时进行了更新, 更新内容是:"
        cat "$LinaRoot/update.lock"
        rm -f "$LinaRoot/update.lock"
        echo ""
    }
    (cd "$LinaRoot" && /system/bin/sh lina-update > /dev/null 2>&1 &)
}

G=${GRAY}
F=$'\e[0m\e[1m'

paint() {
    sed -e "s/%F/$F/g" \
        -e "s/%G/$G/g"
}

banner() {
    cat << 'EOF' | paint

%G  .---.    %F.-./`)%G ,---.   .--.   ____     
%G  | %F,_%G|    %F\ .-.')%G|    \  |  | .'  __ `.  
%G%F,-./  )    / `-' \%G|  ,  \ |  |/   '  \  \ 
%G%F\  '_ '`)   `-'`-`%G|  |\_ \|  ||___|  /  | 
%G%F > (_)  )%G   .---. |  %F_( )_%G\  |   _.-`   | 
%G%F(  .  .-'%G   |   | | %F(_ o _)%G  |.'   %F_%G    | 
%G %F`-'`-'%G|___ |   | |  %F(_,_)%G\  ||  %F_( )_%G  | 
%G  |        \|   | |  |    |  |\ %F(_ o _)%G / 
%G  `--------`'---' '--'    '--' '.%F(_,_)%G.'  

EOF
}

usage() {
    cat << EOF
$Self $YELLOW($GitBranch)$COFF $GRAY$LINA_VERSION$COFF

$BOLD用法: $Self [模块=core] <指令> [参数...]$COFF
$BOLD指令:$COFF
EOF

    MaxLen=0
    for ModPath in "$Modules"/*; do
        [[ -d $ModPath ]] || continue
        Name="${ModPath##*/}"
        Len=${#Name}
        ((Len > MaxLen)) && MaxLen=$Len
    done
    ((Pad = MaxLen + 1))

    for ModPath in "$Modules"/*; do
        [[ -d $ModPath ]] || continue
        ModName="${ModPath##*/}"
        CmdList=""

        for Script in "$ModPath"/*; do
            [[ -d $Script ]] && continue
            [[ -x $Script ]] || continue
            [[ ${Script##*/} == *.* ]] && continue
            CmdList="$CmdList, ${Script##*/}"
        done

        printf "  $GREEN%-${Pad}s$COFF %s\n" "$ModName" "${CmdList#, }"
    done

    exit "${1:-0}"
}

[[ -z $1 ]] && {
    banner
    usage 0
}

Command="$1"

Script="$Modules/core/$Command"
if [[ -x $Script ]]; then
    shift
    export LINA_ENTRY="$Self"
    export LINA_ACTION="$Command"
    exec "$Script" "$@"

elif [[ -d $Modules/$Command ]]; then
    SubCommand="$2"
    case "$SubCommand" in
        # 输入了模块名称, 但未提供指令
        "" | --help | -h)
            usage 0
            ;;
    esac

    if [[ -x $Modules/$Command/$SubCommand ]]; then
        shift 2
        export LINA_ENTRY="$Self"
        export LINA_ACTION="$Command"
        exec "$Modules/$Command/$SubCommand" "$@"
    else
        printf "'%s' 不是模块 '%s' 的指令\n" "$SubCommand" "$Command"
        exit 1
    fi

else
    printf "'%s' 不是 $Self 中的指令或模块, 确定安装它了吗?\n" "$Command"
    exit 1
fi
