#!/usr/bin/env bash

# @ui COFF=0m BOLD=1m FAINT=2m ITALIC=3m ULINE=4m INVERT=7m HIDE=8m DLINE=9m

# @ui RED=31m     GREEN=32m     YELLOW=33m     BLUE=34m     MAGENTA=35m     CYAN=36m     WHITE=37m GRAY=90m
# @ui bgRED=41m   bgGREEN=42m   bgYELLOW=43m   bgBLUE=44m   bgMAGENTA=45m   bgCYAN=46m   bgWHITE=47m
# @ui FOFF=39m BOFF=49m

# @off

set -euo pipefail
shopt -s inherit_errexit 2> /dev/null || true

# shellcheck shell=bash

LINA_ROOT="$(dirname "$(readlink -f "$0")")"
LINA_VERSION="r$(git -C "$LINA_ROOT" rev-list --count HEAD)-$(git -C "$LINA_ROOT" rev-parse --short HEAD)"
GIT_BRANCH="$(git -C "$LINA_ROOT" rev-parse --abbrev-ref HEAD)"

export LINA_ROOT
export LINA_VERSION
export GIT_BRANCH
export MODS_DIR="$LINA_ROOT/cells"
export DEFAULT_MOD="core"
# export WORKER_DIR="/data/local/lina"
export WORKER_DIR="$LINA_ROOT/data"

SELF_PATH=$(realpath "${BASH_SOURCE[0]}") SELF="${SELF_PATH##*/}"

init_ui() {
    [[ ! -t 1 && -z $FORCE_COLOR ]] && return
    local line pair key val ansi_header=$'\e['
    while read -r line; do
        [[ $line == "# @off"* ]] && return
        [[ $line == "# @ui "* ]] && for pair in ${line#\# @ui }; do
            key="${pair%%=*}" val="${pair#*=}"
            declare -g "${key}=${ansi_header}${val}"
        done
    done < "$SELF_PATH"

    export hl="${CYAN}${INVERT}"
    export off="${COFF}"
}

update() {
    [[ -f "$LINA_ROOT/.lina-dev" ]] || {
        if [[ -s "$LINA_ROOT/update.lock" ]]; then
            echo "$SELF 上次启动时进行了更新, 更新内容是:"
            cat "$LINA_ROOT/update.lock"
            echo ""
        fi
        rm -f "$LINA_ROOT/update.lock"
        (bash "$LINA_ROOT/repo-update" --repo "$LINA_ROOT" --output "$LINA_ROOT/update.lock" -f > /dev/null 2>&1 &)
    }
}

banner() {
    # shellcheck disable=SC2016
    printf '%b' '  \e[2m.---.    \e[33;22;1m.-./`) \e[0m\e[2m,---.   .--.   ____     \e[0m\n' \
        '  \e[2m| \e[33;22;1m,_\e[0m\e[2m|    \e[33;22;1m\\ \e[32m.-.\e[33m'\'')\e[0m\e[2m|    \\  |  | .'\''  __ `.  \e[0m\n' \
        '\e[33;1m,-./  )    / \e[32m`-'\'' \e[33m\\\e[0m\e[2m|  ,  \\ |  |/   '\''  \\  \\ \e[0m\n' \
        '\e[33;1m\\  '\''\e[32m_ \e[33m'\''`)   `-'\''`-`\e[0m\e[2m|  |\\\e[33;22;1m_ \e[0m\e[2m\\|  ||___|  /  | \e[0m\n' \
        ' \e[33;1m> \e[32m(_)  \e[33m)   \e[0m\e[2m.---. |  \e[33;22;1m_( )_\e[0m\e[2m\\  |   _.-`   | \e[0m\n' \
        '\e[33;1m(  .  .-'\''   \e[0m\e[2m|   | | \e[33;22;1m(_ \e[32mo \e[33m_)  \e[0m\e[2m|.'\''   \e[33;22;1m_    \e[0m\e[2m| \e[0m\n' \
        ' \e[33;1m`-'\''`-'\''\e[0m\e[2m|___ |   | |  \e[33;22;1m(_,_)\e[0m\e[2m\\  ||  \e[33;22;1m_( )_  \e[0m\e[2m| \e[0m\n' \
        '  \e[2m|        \\|   | |  |    |  |\\ \e[33;22;1m(_ \e[32mo \e[33m_) \e[0m\e[2m/ \e[0m\n' \
        '  \e[2m`--------`'\''---'\'' '\''--'\''    '\''--'\'' '\''.\e[33;22;1m(_,_)\e[0m\e[2m.'\''  \e[0m\n' \
        '                                          \n'
}

usage() {
    cat << EOF
${SELF} ${YELLOW}(${GIT_BRANCH})${COFF} ${GRAY}${LINA_VERSION}${COFF}

${BOLD}用法: ${SELF} [模块=${DEFAULT_MOD}] <指令> [参数...]${COFF}
${BOLD}指令:${COFF}
EOF

    local maxlen=0 modpath name len pad modname cmdlist script
    for modpath in "$MODS_DIR"/*; do
        [[ -d $modpath ]] || continue
        name="${modpath##*/}"
        len=${#name}
        ((len > maxlen)) && maxlen=$len
    done
    ((pad = maxlen + 1))

    for modpath in "$MODS_DIR"/*; do
        [[ -d $modpath ]] || continue
        modname="${modpath##*/}"
        cmdlist=""

        for script in "$modpath"/*; do
            [[ -d $script ]] && continue
            [[ -x $script ]] || continue
            [[ ${script##*/} == *.* ]] && continue
            cmdlist="$cmdlist, ${script##*/}"
        done

        printf "  $GREEN%-${pad}s$COFF %s\n" "$modname" "${cmdlist#, }"
    done

    exit "${1:-0}"
}

dispatch() {
    [[ -z ${1:-} ]] && {
        banner
        usage 0
    }

    local command="$1"
    local script="$MODS_DIR/${DEFAULT_MOD}/$command"

    if [[ -x $script ]]; then
        shift

        export LINA_ENTRY="$SELF"
        export LINA_ACTION="$command"
        exec "$script" "$@"

    elif [[ -d $MODS_DIR/$command ]]; then
        local subcommand="$2"
        case "$subcommand" in
            "" | --help | -h)
                usage 0
                ;;
        esac

        if [[ -x $MODS_DIR/$command/$subcommand ]]; then
            shift 2

            export LINA_ENTRY="$SELF"
            export LINA_ACTION="$command"
            exec "$MODS_DIR/$command/$subcommand" "$@"
        else
            printf "'%s' 不是模块 '%s' 的指令\n" "$subcommand" "$command"
            exit 1
        fi

    else
        printf "'%s' 不是 $SELF 中的指令或模块, 确定安装它了吗?\n" "$command"
        exit 1
    fi
}

main() {
    init_ui
    update
    dispatch "$@"
}
main "$@"
