#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

LinaRoot="$(dirname "$(readlink -f "$0")")"

GitBranch="$(git rev-parse --abbrev-ref HEAD)"
LINA_VERSION="r$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)"

Modules="$LinaRoot/modules"
Self="${0##*/}"

[[ -f "$LinaRoot/.lina-dev" ]] || {
    [[ -f "$LinaRoot/update.lock" ]] && {
        echo "$Self 上次启动时进行了更新, 更新内容是:"
        cat "$LinaRoot/update.lock"
        rm -f "$LinaRoot/update.lock"
        echo ""
    }
    (cd "$LinaRoot" && sh lina-update > /dev/null 2>&1 &)
}

G=$'\e[38;5;243m'
W=$'\e[0m'
B=$'\e[1m'

C_GRAY=$'\e[38;5;243m'
C_GREEN=$'\e[32m'
C_YELLOW=$'\e[33m'
C_RESET=$'\e[0m'
C_BLOD=$'\e[1m'

paint() {
    sed -e "s/%B/$B/g" \
        -e "s/%G/$G/g" \
        -e "s/%W/$W/g"
}

if [[ -z $1 ]]; then
    cat << 'EOF' | paint

%G  .---.    %W%B.-./`)%W%G ,---.   .--.   ____     %W
%G  | %W%B,_%W%G|    %W%B\ .-.')%W%G|    \  |  | .'  __ `.  %W
%G%W%B,-./  )    / `-' \%W%G|  ,  \ |  |/   '  \  \ %W
%G%W%B\  '_ '`)   `-'`"`%W%G|  |\_ \|  ||___|  /  | %W
%G%W%B > (_)  )%W%G   .---. |  %W%B_( )_%W%G\  |   _.-`   | %W
%G%W%B(  .  .-'%W%G   |   | | %W%B(_ o _)%W%G  |.'   %W%B_%W%G    | %W
%G %W%B`-'`-'%W%G|___ |   | |  %W%B(_,_)%W%G\  ||  %W%B_( )_%W%G  | %W
%G  |        \|   | |  |    |  |\ %W%B(_ o _)%W%G / %W
%G  `--------`'---' '--'    '--' '.%W%B(_,_)%W%G.'  %W

EOF

    cat << EOF
$Self $C_YELLOW($GitBranch)$C_RESET $C_GRAY$LINA_VERSION$C_RESET

$C_BLOD用法: $Self [模块=core] <指令> [参数...]$C_RESET
$C_BLOD指令:$C_RESET
EOF

    MaxLen=0
    for ModPath in "$Modules"/*; do
        [[ -d $ModPath ]] || continue
        Name="${ModPath##*/}"
        Len=${#Name}
        ((Len > MaxLen)) && MaxLen=$Len
    done
    ((Pad = MaxLen + 1))

    for ModPath in "$Modules"/*; do
        [[ -d $ModPath ]] || continue
        ModName="${ModPath##*/}"
        CmdList=""

        for Script in "$ModPath"/*; do
            [[ -d $Script ]] && continue
            [[ -x $Script ]] || continue
            [[ ${Script##*/} == *.* ]] && continue
            CmdList="$CmdList, ${Script##*/}"
        done

        printf "  $C_GREEN%-${Pad}s$C_RESET %s\n" "$ModName" "${CmdList#, }"
    done

    exit 0
fi

Command="$1"

printf "你输入了 %s, 对应的逻辑还没有完成" $Command
