#!/system/bin/sh

# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

(($(id -u) != 0)) && exec su --mount-master -c "$(printf "%q " "$(readlink -f "$0")" "$@")"
ScriptDir=$(dirname "$0")
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
export PATH="/data/data/com.termux/files/usr/bin:$PATH"
[[ -f "$ScriptDir/lib/ui.sh" ]] || {
    echo "错误: 未找到 $ScriptDir/lib/ui.sh" >&2
    exit 1
}
source "$ScriptDir/lib/ui.sh"

BasePath="/data/local/chroot"
DisplayCmd="${LINA_ENTRY:+$LINA_ENTRY $LINA_ACTION}"
DisplayCmd="${DisplayCmd:-${0##*/}}"

usage() {
    cat << EOF
归档 chroot 根文件系统。

用法: $DisplayCmd <Name> <BackupDir>

参数:
  Name         chroot 环境的名称
  BackupDir    归档文件存放的目标目录
EOF
    exit 1
}

Name="$1"
BackupDir="$2"
[[ -z $Name ]] && {
    m1err "未提供名称。"
    usage
}
[[ -z $BackupDir ]] && {
    m1err "未提供备份目录。"
    usage
}

mkdir -p "$BackupDir"
RootFs="$BasePath/$Name"
[[ -d $RootFs ]] || {
    m1err "目录 '$RootFs' 不存在。"
    exit 1
}

TermuxTmp="/data/data/com.termux/files/usr/tmp"
TarExcludeOpts=()
DuExcludeOpts=()

if "$ScriptDir"/is-mounted "$TermuxTmp" "$RootFs/tmp"; then
    TarExcludeOpts+=(--exclude="$(basename "$RootFs")/tmp")
    DuExcludeOpts+=(--exclude="$RootFs/tmp")
fi

m1 "统计存储占用..."
RawSize=$(du -sbx "${DuExcludeOpts[@]}" "$RootFs" 2> /dev/null | awk '{print $1}')
HumanSize=$(du -shx "${DuExcludeOpts[@]}" "$RootFs" 2> /dev/null | awk '{print $1}')

m1 "开始归档..."
BackupFile="$BackupDir/$Name-$(date +'[%y]%m.%d-%H:%M:%S').tar.zst"
m2 "%s %s -> %s" "$HumanSize" "$Name" "$BackupFile"

tar -cpf - \
    --one-file-system --warning=no-file-ignored \
    "${TarExcludeOpts[@]}" \
    -C "$(dirname "$RootFs")" \
    "$(basename "$RootFs")" 2> /dev/null |
    if command -v pv > /dev/null; then pv -s "$RawSize"; else cat; fi |
    zstd -T0 > "$BackupFile"

if [[ -f $BackupFile ]]; then
    m1 "归档完成。"
else
    m1warn "归档文件未生成。"
    exit 1
fi
