#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

(($(id -u) != 0)) && exec su --mount-master -c "$(printf "%q " "$(readlink -f "$0")" "$@")"
ScriptDir=$(dirname "$0")
[[ -f "$ScriptDir/lib/ui.sh" ]] || {
    echo "错误: 未找到 $ScriptDir/lib/ui.sh" >&2
    exit 1
}
source "$ScriptDir/lib/ui.sh"

BasePath="/data/local/chroot"
DisplayCmd="${LINA_ENTRY:+$LINA_ENTRY $LINA_ACTION}"
DisplayCmd="${DisplayCmd:-${0##*/}}"

usage() {
    cat << EOF
挂载 chroot 文件系统。

用法: $DisplayCmd <Name>

参数:
  Name    chroot 环境的名称
EOF
    exit 1
}

Name="$1"
[[ -z $Name ]] && {
    m1err "未提供名称。"
    usage 1
}
RootFs="$BasePath/$Name"
[[ -d $RootFs ]] || {
    m1err "目录 '$RootFs' 不存在。"
    exit 1
}

try_mount() {
    local src="$1" tgt="$2"
    shift 2

    if "$ScriptDir"/is-mounted "$src" "$tgt"; then
        m2yellow "跳过: %s" "$tgt"
    else
        if mount "$@" "$src" "$tgt" 2> /dev/null; then
            m2green "成功: %s" "$tgt"
        else
            m2err "失败: %s" "$tgt"
        fi
    fi
}

# /data
if mount -o remount,dev,suid /data; then
    m2green "成功: remount /data (dev,suid)"
else
    m2err "失败: remount /data (dev,suid)"
fi

# /tmp
TERMUX_TMP="/data/data/com.termux/files/usr/tmp"
CHROOT_TMP="$RootFs/tmp"
mkdir -p "$TERMUX_TMP"
chmod 1777 "$TERMUX_TMP"
mkdir -p "$CHROOT_TMP"
try_mount "$TERMUX_TMP" "$CHROOT_TMP" --bind

# /dev /dev/pts /dev/shm /proc /sys /sdcard
try_mount /dev "$RootFs/dev" --bind
mkdir -p "$RootFs/dev/pts" "$RootFs/dev/shm" \
    "$RootFs/proc" "$RootFs/sys" "$RootFs/sdcard"
try_mount devpts "$RootFs/dev/pts" -t devpts
try_mount tmpfs "$RootFs/dev/shm" -t tmpfs -o mode=1777,size=512m
try_mount proc "$RootFs/proc" -t proc
try_mount sysfs "$RootFs/sys" -t sysfs
try_mount /sdcard "$RootFs/sdcard" --bind
