#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

if [ "$(id -u)" -ne 0 ]; then
    current_script="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
    quoted_args=$(printf " %q" "$@")
    exec su -M -c "exec '$current_script'$quoted_args"
fi
ScriptDir="$(cd "$(dirname "$0")" && pwd)"

# 启用此段以使用 makepkg 风格输出
if [[ ! -f "$ScriptDir/lib/message.sh" ]]; then
    echo "错误: 未找到 $ScriptDir/lib/message.sh" >&2
    exit 1
fi
source "$ScriptDir/lib/message.sh"
QUIET=0
colorize

# 启用以下两行以使用 Termux 中的二进制程序和库
#export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
#PATH="/data/data/com.termux/files/usr/bin:$PATH"

BasePath="/data/local/chroot"
DisplayCmd="${LINA_ENTRY:+$LINA_ENTRY $LINA_ACTION}"
DisplayCmd="${DisplayCmd:-${0##*/}}"

usage() {
    cat << EOF
删除 chroot 根文件系统。

用法: $DisplayCmd <Name>

参数:
  Name         chroot 环境的名称
EOF
    exit 1
}

Name="$1"
[[ -z $Name ]] && {
    error "未提供名称。"
    usage
}

RootFs="$BasePath/$Name"
[[ -d $RootFs ]] || {
    error "目录 '$RootFs' 不存在。"
    exit 1
}

if $ScriptDir/checkmount "$Name" > /dev/null 2>&1; then
    error "必须先卸载文件系统才能删除。"
    exit 1
fi

warning "虽然未检测到挂载, 但是此命令可能不可靠, 建议手动检查挂载状态。"
warning "即将执行 rm -rf %s" "$RootFs"

printf "确定要删除 '%s' 吗? [y/N] " "$Name"
read -r -n 1 ans
echo

case "$ans" in
    [yY])
        rm -rf "$RootFs"
        echo "$Name"
        ;;
    *)
        exit 0
        ;;
esac
