#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

(($(id -u) != 0)) && exec su --mount-master -c "$(printf "%q " "$(readlink -f "$0")" "$@")"
ScriptDir=$(dirname "$0")
[[ -f "$ScriptDir/lib/ui.sh" ]] || {
    echo "错误: 未找到 $ScriptDir/lib/ui.sh" >&2
    exit 1
}
source "$ScriptDir/lib/ui.sh"

BasePath="/data/local/chroot"
DisplayCmd="${LINA_ENTRY:+$LINA_ENTRY $LINA_ACTION}"
DisplayCmd="${DisplayCmd:-${0##*/}}"

usage() {
    cat << EOF
删除 chroot 根文件系统。

用法: $DisplayCmd <Name>

参数:
  Name         chroot 环境的名称
EOF
    exit 1
}

Name="$1"
[[ -z $Name ]] && {
    m1err "未提供名称。"
    usage
}

RootFs="$BasePath/$Name"
[[ -d $RootFs ]] || {
    m1err "目录 '$RootFs' 不存在。"
    exit 1
}

if "$ScriptDir"/checkmount "$Name" > /dev/null 2>&1; then
    m1err "必须先卸载文件系统才能删除。"
    exit 1
fi

m1warn "虽然未检测到挂载, 但是此命令可能不可靠, 建议手动检查挂载状态。"
m1warn "即将执行 rm -rf %s" "$RootFs"

printf "确定要删除 '%s' 吗? [y/N] " "$Name"
read -r -n 1 ans
echo

case "$ans" in
    [yY])
        rm -rf "$RootFs"
        echo "$Name"
        ;;
    *)
        exit 0
        ;;
esac
