#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

if [ "$(id -u)" -ne 0 ]; then
    current_script="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
    quoted_args=$(printf " %q" "$@")
    exec su -M -c "exec '$current_script'$quoted_args"
fi
ScriptDir="$(cd "$(dirname "$0")" && pwd)"

# 启用此段以使用 makepkg 风格输出
if [[ ! -f "$ScriptDir/lib/message.sh" ]]; then
    echo "错误: 未找到 $ScriptDir/lib/message.sh" >&2
    exit 1
fi
source "$ScriptDir/lib/message.sh"
QUIET=0
colorize

# 启用此行以使用其它自定义脚本
PATH="$ScriptDir:$PATH"
# 启用以下两行以使用 Termux 中的二进制程序和库
#export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
#PATH="/data/data/com.termux/files/usr/bin:$PATH"

BasePath="/data/local/chroot"
DisplayCmd="${LINA_ENTRY:+$LINA_ENTRY $LINA_ACTION}"
DisplayCmd="${DisplayCmd:-${0##*/}}"

usage() {
    cat << EOF
安全终止 chroot 环境，包括清理进程并卸载挂载点。

用法:
  $DisplayCmd <Name>   终止指定名称的环境
  $DisplayCmd -a       终止所有环境

参数:
  Name    chroot 环境的名称

选项:
  -a      选择所有 chroot 环境
EOF
    exit 1
}

chroot_shutdown() {
    local target="$1"
    local rootfs="$BasePath/$target"

    [[ -d $rootfs ]] || {
        error "目录 '$rootfs' 不存在，跳过。"
        return 1
    }

    msg "终止: $target ..."

    # 尝试杀死相关进程
    chroot-proc "$target" ka > /dev/null 2>&1

    # 卸载挂载点
    chroot-umount "$target" > /dev/null 2>&1
}

if [[ $1 == "-a" ]]; then
    [[ -n $2 ]] && {
        error "选项 -a 不能与名称共存。"
        usage
    }

    if [ -d "$BasePath" ]; then
        for dir in "$BasePath"/*; do
            if [ -d "$dir" ]; then
                chroot_shutdown "${dir##*/}"
            fi
        done
    else
        error "目录 '$BasePath' 不存在。"
        exit 1
    fi

elif [[ -n $1 ]]; then
    [[ $1 == -* ]] && usage

    Name="$1"
    RootFs="$BasePath/$Name"
    [[ -d $RootFs ]] || {
        error "目录 '$RootFs' 不存在。"
        exit 1
    }
    chroot_shutdown "$Name"
else
    usage
fi

Pfx="${LINA_ENTRY:+$LINA_ENTRY }"
Pfx="${Pfx:-chroot-}"

echo ""
plain "提示信息:"
plain "  使用 '${Pfx}ps' 命令以确认"
plain "  此命令可能不可靠，应该手动确认环境是否完全清理。"
