#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

if [ "$(id -u)" -ne 0 ]; then
    current_script="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
    quoted_args=$(printf " %q" "$@")
    exec su -M -c "exec '$current_script'$quoted_args"
fi
ScriptDir="$(cd "$(dirname "$0")" && pwd)"

# 启用此段以使用 makepkg 风格输出
if [[ ! -f "$ScriptDir/lib/message.sh" ]]; then
    echo "错误: 未找到 $ScriptDir/lib/message.sh" >&2
    exit 1
fi
source "$ScriptDir/lib/message.sh"
QUIET=0
colorize

# 启用以下两行以使用 Termux 中的二进制程序和库
#export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
#PATH="/data/data/com.termux/files/usr/bin:$PATH"

BasePath="/data/local/chroot"
DisplayCmd="${LINA_ENTRY:+$LINA_ENTRY $LINA_ACTION}"
DisplayCmd="${DisplayCmd:-${0##*/}}"

usage() {
    cat << EOF
卸载 chroot 文件系统。

用法: $DisplayCmd <Name>

参数:
  Name    chroot 环境的名称
EOF
    exit 1
}

Name="$1"
[[ -z $Name ]] && {
    error "未提供名称。"
    usage 1
}
RootFs="$BasePath/$Name"
[[ -d $RootFs ]] || {
    error "目录 '$RootFs' 不存在。"
    exit 1
}

try_umount_stacked() {
    local target_path="$1"
    local unmounted_count=0

    while umount -l "$target_path" 2> /dev/null; do
        unmounted_count=$((unmounted_count + 1))

        if [ "$unmounted_count" -ge 50 ]; then
            error "无法卸载 %s, 重试次数达到 50 次" "$target_path"
            exit 1
        fi

        msg2g "卸载[%s]: %s" "$unmounted_count" "$target_path"
    done

    if [ ! "$unmounted_count" -gt 0 ]; then
        msg2y "跳过: %s" "$target_path"
    fi
}

try_umount_stacked "$RootFs/tmp"
try_umount_stacked "$RootFs/sdcard"
try_umount_stacked "$RootFs/sys"
try_umount_stacked "$RootFs/proc"
try_umount_stacked "$RootFs/dev/shm"
try_umount_stacked "$RootFs/dev/pts"
try_umount_stacked "$RootFs/dev"
